[".oh-my-bash"]
type = "archive"
url = "https://github.com/ohmybash/oh-my-bash/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".nvm"]
type = "git-repo"
refreshPeriod = "168h"
url = "https://github.com/nvm-sh/nvm"

[".vim/colors/nord.vim"]
type = "file"
url = "https://github.com/nordtheme/vim/raw/main/colors/nord.vim"

# https://github.com/thjbdvlt/spell-fr.vim
[".config/nvim/spell/fr.utf-8.spl"]
type = "file"
refreshPeriod = "672h"
url = "https://raw.githubusercontent.com/thjbdvlt/spell-fr.vim/sea/vim/st.utf-8.spl"

["bin/dynamicwallpaperconverter"]
type = "file"
executable = true
url = "https://raw.githubusercontent.com/zzag/plasma5-wallpapers-dynamic-extras/master/dynamicwallpaperconverter"

["bin/snyk"]
type = "file"
executable = true
refreshPeriod = "672h"
url = "https://static.snyk.io/cli/latest/snyk-linux"


# ["bin/trunk"]
# type = "file"
# url = "https://trunk.io/releases/trunk"
# executable = true

[".local/share/icons/hicolor/48x48/apps/neovide.png"]
type = "file"
url = "https://github.com/neovide/neovide/raw/main/assets/neovide-48x48.png"

[".local/share/icons/hicolor/scalable/apps/neovide.svg"]
type = "file"
url = "https://github.com/neovide/neovide/raw/main/assets/neovide.svg"
