[".oh-my-bash"]
type = "archive"
url = "https://github.com/ohmybash/oh-my-bash/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".vim/colors/nord.vim"]
type = "file"
url = "https://github.com/nordtheme/vim/raw/main/colors/nord.vim"

["bin/dynamicwallpaperconverter"]
type = "file"
url = "https://raw.githubusercontent.com/zzag/plasma5-wallpapers-dynamic-extras/master/dynamicwallpaperconverter"
executable = true

[".local/share/icons/hicolor/48x48/apps/neovide.svg"]
type = "file"
url = "https://github.com/neovide/neovide/raw/main/assets/neovide-48x48.png"

[".local/share/icons/hicolor/scalable/apps/neovide.svg"]
type = "file"
url = "https://github.com/neovide/neovide/raw/main/assets/neovide.svg"
