[".oh-my-bash"]
type = "archive"
url = "https://github.com/ohmybash/oh-my-bash/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

["bin/dynamicwallpaperconverter"]
type = "file"
url = "https://raw.githubusercontent.com/zzag/plasma5-wallpapers-dynamic-extras/master/dynamicwallpaperconverter"
executable = true
