[".oh-my-bash"]
type = "archive"
url = "https://github.com/ohmybash/oh-my-bash/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".nvm"]
type = "git-repo"
refreshPeriod = "168h"
url = "https://github.com/nvm-sh/nvm"

["bin/"]
type = "archive"
include = ["git-credential-manager", "libHarfBuzzSharp.so", "libSkiaSharp.so"]
url = "https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.5.1/gcm-linux_amd64.2.5.1.tar.gz"

[".local/share/fonts/VictorMono"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/VictorMono.tar.xz"

["bin/dynamicwallpaperconverter"]
type = "file"
executable = true
url = "https://raw.githubusercontent.com/zzag/plasma5-wallpapers-dynamic-extras/master/dynamicwallpaperconverter"

[".vim/colors/nord.vim"]
type = "file"
url = "https://github.com/nordtheme/vim/raw/main/colors/nord.vim"

[".config/nvim/spell/fr.utf-8.spl"]
# https://github.com/thjbdvlt/spell-fr.vim
type = "file"
refreshPeriod = "672h"
url = "https://raw.githubusercontent.com/thjbdvlt/spell-fr.vim/sea/vim/st.utf-8.spl"

[".local/share/icons/hicolor/48x48/apps/neovide.png"]
type = "file"
url = "https://github.com/neovide/neovide/raw/main/assets/neovide-48x48.png"

[".local/share/icons/hicolor/scalable/apps/neovide.svg"]
type = "file"
url = "https://github.com/neovide/neovide/raw/main/assets/neovide.svg"
