#!/usr/bin/env bash
# shellcheck disable=SC1090,SC1091,SC2034

# HISTORY
shopt -s histappend # append to history file
# Ignore duplicates & limit file size
export HISTFILESIZE=2000
export HISTCONTROL=ignoredups:erasedups

export EDITOR='nvim'
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/share/bob/nvim-bin:$PATH"

# HACK: Cannot just `chsh -s /bin/nu` due to https://github.com/sddm/sddm/issues/1768.
# export SHELL=/bin/nu
# nu
