#!/usr/bin/env bash

[[ -f ~/.bashrc ]] && . ~/.bashrc
. "$HOME/.cargo/env"

# Added by Toolbox App
export PATH="$PATH:$HOME/.local/share/JetBrains/Toolbox/scripts"

export DVM_DIR="$HOME/.dvm"
export PATH="$DVM_DIR/bin:$PATH"

# >>> coursier install directory >>>
export PATH="$PATH:$HOME/.local/share/coursier/bin"
# <<< coursier install directory <<<
