#!/bin/bash
set -eo pipefail

if [[ -x "$(command -v mise)" ]]; then
	mise p up -y
	mise up -y
fi

if [[ -x "$(command -v bob)" ]]; then
	bob update --all
fi

# Update some autogenerated scripts
# HINT: https://unix.stackexchange.com/questions/45201/bash-what-does-do/45203#45203
atuin init nu >|~/.config/nushell/scripts/integrations/atuin.nu
starship init nu >|~/.config/nushell/scripts/integrations/starship.nu
mise activate nu >|~/.config/nushell/scripts/integrations/mise.nu
