#!/bin/bash
# Update some autogenerated scripts

mkdir -p ~/.cache/atuin
rm -rf ~/.cache/atuin/init.nu
atuin init nu > ~/.cache/atuin/init.nu

mkdir -p ~/.cache/starship
rm -rf ~/.cache/starship/init.nu
starship init nu > ~/.cache/starship/init.nu

mkdir -p ~/.cache/mise
rm -rf ~/.cache/mise/init.nu
mise activate nu > ~/.cache/mise/init.nu
