gui:
  showBottomLine: false
  border: rounded
  nerdFontsVersion: "3"
  spinner:
    #NOTE: https://stackoverflow.com/questions/2685435/cooler-ascii-spinners
    frames:
      - "🌑"
      - "🌒"
      - "🌓"
      - "🌔"
      - "🌕"
      - "🌖"
      - "🌗"
      - "🌘"
    rate: 80
git:
  parseEmoji: true
  paging:
    externalDiffCommand: difft --color=always --display=inline
os:
  editPreset: nvim
