neovim-bin = "/home/tobi/.local/share/bob/nvim-bin/nvim"

[font]
normal = ["VictorMono Nerd Font"]
size = 13.2

[font.features]
VictorMonoNF-Regular = [
    "ss01",
    "ss02",
    "ss03",
    "ss04",
    "ss05",
    "ss06",
    "ss07",
    "ss0",
]
