[metadata]
name = "zellij-sessions"
description = "List zellij sessions"
requirements = ["zellij"]

[source]
ansi = true
command = "zellij list-sessions"
output = "zellij a {strip_ansi|split: :0}"
watch = 5

[keybindings]
ctrl-q = "actions:delete"

[actions.delete]
description = "Kill the selected session"
command = "zellij d {strip_ansi|split: :0}"
mode = "fork"
